// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package cbsiface provides an interface to enable mocking the Cloud Virtual Machine CBS service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package cbsiface

import (
	"github.com/polefishu/sdk-builder/sdf"
	"github.com/polefishu/sdk-builder/sdf/request"
	"github.com/polefishu/sdk-builder/service/cbs"
)

// CBSAPI provides an interface to enable mocking the
// cbs.CBS service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // Cloud Virtual Machine CBS.
//    func myFunc(svc cbsiface.CBSAPI) bool {
//        // Make svc.DescribeCbsStorages request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := cbs.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockCBSClient struct {
//        cbsiface.CBSAPI
//    }
//    func (m *mockCBSClient) DescribeCbsStorages(input *cbs.DescribeCbsStoragesInput) (*cbs.DescribeCbsStoragesOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockCBSClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type CBSAPI interface {
	DescribeCbsStorages(*cbs.DescribeCbsStoragesInput) (*cbs.DescribeCbsStoragesOutput, error)
	DescribeCbsStoragesWithContext(sdf.Context, *cbs.DescribeCbsStoragesInput, ...request.Option) (*cbs.DescribeCbsStoragesOutput, error)
	DescribeCbsStoragesRequest(*cbs.DescribeCbsStoragesInput) (*request.Request, *cbs.DescribeCbsStoragesOutput)
}

var _ CBSAPI = (*cbs.CBS)(nil)
