// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package dfw

import (
	"github.com/polefishu/sdk-builder/sdf"
	"github.com/polefishu/sdk-builder/sdf/request"
	"github.com/polefishu/sdk-builder/sdf/sdfutil"
)

const opCreateSecurityGroup = "CreateSecurityGroup"

// CreateSecurityGroupRequest generates a "aws/request.Request" representing the
// client's request for the CreateSecurityGroup operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See CreateSecurityGroup for more information on using the CreateSecurityGroup
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the CreateSecurityGroupRequest method.
//    req, resp := client.CreateSecurityGroupRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) CreateSecurityGroupRequest(input *CreateSecurityGroupInput) (req *request.Request, output *CreateSecurityGroupOutput) {
	op := &request.Operation{
		Name:       opCreateSecurityGroup,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
	}

	if input == nil {
		input = &CreateSecurityGroupInput{}
	}

	output = &CreateSecurityGroupOutput{}
	req = c.newRequest(op, input, output)
	return
}

// CreateSecurityGroup API operation for SecurityGroup.
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation CreateSecurityGroup for usage and error information.
func (c *DFW) CreateSecurityGroup(input *CreateSecurityGroupInput) (*CreateSecurityGroupOutput, error) {
	req, out := c.CreateSecurityGroupRequest(input)
	return out, req.Send()
}

// CreateSecurityGroupWithContext is the same as CreateSecurityGroup with the addition of
// the ability to pass a context and additional request options.
//
// See CreateSecurityGroup for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) CreateSecurityGroupWithContext(ctx sdf.Context, input *CreateSecurityGroupInput, opts ...request.Option) (*CreateSecurityGroupOutput, error) {
	req, out := c.CreateSecurityGroupRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opCreateSecurityGroupPolicy = "CreateSecurityGroupPolicy"

// CreateSecurityGroupPolicyRequest generates a "aws/request.Request" representing the
// client's request for the CreateSecurityGroupPolicy operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See CreateSecurityGroupPolicy for more information on using the CreateSecurityGroupPolicy
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the CreateSecurityGroupPolicyRequest method.
//    req, resp := client.CreateSecurityGroupPolicyRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) CreateSecurityGroupPolicyRequest(input *CreateSecurityGroupPolicyInput) (req *request.Request, output *CreateSecurityGroupPolicyOutput) {
	op := &request.Operation{
		Name:       opCreateSecurityGroupPolicy,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
	}

	if input == nil {
		input = &CreateSecurityGroupPolicyInput{}
	}

	output = &CreateSecurityGroupPolicyOutput{}
	req = c.newRequest(op, input, output)
	return
}

// CreateSecurityGroupPolicy API operation for SecurityGroup.
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation CreateSecurityGroupPolicy for usage and error information.
func (c *DFW) CreateSecurityGroupPolicy(input *CreateSecurityGroupPolicyInput) (*CreateSecurityGroupPolicyOutput, error) {
	req, out := c.CreateSecurityGroupPolicyRequest(input)
	return out, req.Send()
}

// CreateSecurityGroupPolicyWithContext is the same as CreateSecurityGroupPolicy with the addition of
// the ability to pass a context and additional request options.
//
// See CreateSecurityGroupPolicy for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) CreateSecurityGroupPolicyWithContext(ctx sdf.Context, input *CreateSecurityGroupPolicyInput, opts ...request.Option) (*CreateSecurityGroupPolicyOutput, error) {
	req, out := c.CreateSecurityGroupPolicyRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeleteSecurityGroup = "DeleteSecurityGroup"

// DeleteSecurityGroupRequest generates a "aws/request.Request" representing the
// client's request for the DeleteSecurityGroup operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See DeleteSecurityGroup for more information on using the DeleteSecurityGroup
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the DeleteSecurityGroupRequest method.
//    req, resp := client.DeleteSecurityGroupRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) DeleteSecurityGroupRequest(input *DeleteSecurityGroupInput) (req *request.Request, output *DeleteSecurityGroupOutput) {
	op := &request.Operation{
		Name:       opDeleteSecurityGroup,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
	}

	if input == nil {
		input = &DeleteSecurityGroupInput{}
	}

	output = &DeleteSecurityGroupOutput{}
	req = c.newRequest(op, input, output)
	return
}

// DeleteSecurityGroup API operation for SecurityGroup.
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation DeleteSecurityGroup for usage and error information.
func (c *DFW) DeleteSecurityGroup(input *DeleteSecurityGroupInput) (*DeleteSecurityGroupOutput, error) {
	req, out := c.DeleteSecurityGroupRequest(input)
	return out, req.Send()
}

// DeleteSecurityGroupWithContext is the same as DeleteSecurityGroup with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteSecurityGroup for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) DeleteSecurityGroupWithContext(ctx sdf.Context, input *DeleteSecurityGroupInput, opts ...request.Option) (*DeleteSecurityGroupOutput, error) {
	req, out := c.DeleteSecurityGroupRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDeleteSecurityGroupPolicy = "DeleteSecurityGroupPolicy"

// DeleteSecurityGroupPolicyRequest generates a "aws/request.Request" representing the
// client's request for the DeleteSecurityGroupPolicy operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See DeleteSecurityGroupPolicy for more information on using the DeleteSecurityGroupPolicy
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the DeleteSecurityGroupPolicyRequest method.
//    req, resp := client.DeleteSecurityGroupPolicyRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) DeleteSecurityGroupPolicyRequest(input *DeleteSecurityGroupPolicyInput) (req *request.Request, output *DeleteSecurityGroupPolicyOutput) {
	op := &request.Operation{
		Name:       opDeleteSecurityGroupPolicy,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
	}

	if input == nil {
		input = &DeleteSecurityGroupPolicyInput{}
	}

	output = &DeleteSecurityGroupPolicyOutput{}
	req = c.newRequest(op, input, output)
	return
}

// DeleteSecurityGroupPolicy API operation for SecurityGroup.
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation DeleteSecurityGroupPolicy for usage and error information.
func (c *DFW) DeleteSecurityGroupPolicy(input *DeleteSecurityGroupPolicyInput) (*DeleteSecurityGroupPolicyOutput, error) {
	req, out := c.DeleteSecurityGroupPolicyRequest(input)
	return out, req.Send()
}

// DeleteSecurityGroupPolicyWithContext is the same as DeleteSecurityGroupPolicy with the addition of
// the ability to pass a context and additional request options.
//
// See DeleteSecurityGroupPolicy for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) DeleteSecurityGroupPolicyWithContext(ctx sdf.Context, input *DeleteSecurityGroupPolicyInput, opts ...request.Option) (*DeleteSecurityGroupPolicyOutput, error) {
	req, out := c.DeleteSecurityGroupPolicyRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDescribeSecurityGroupPolicys = "DescribeSecurityGroupPolicys"

// DescribeSecurityGroupPolicysRequest generates a "aws/request.Request" representing the
// client's request for the DescribeSecurityGroupPolicys operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See DescribeSecurityGroupPolicys for more information on using the DescribeSecurityGroupPolicys
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the DescribeSecurityGroupPolicysRequest method.
//    req, resp := client.DescribeSecurityGroupPolicysRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) DescribeSecurityGroupPolicysRequest(input *DescribeSecurityGroupPolicysInput) (req *request.Request, output *DescribeSecurityGroupPolicysOutput) {
	op := &request.Operation{
		Name:       opDescribeSecurityGroupPolicys,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
	}

	if input == nil {
		input = &DescribeSecurityGroupPolicysInput{}
	}

	output = &DescribeSecurityGroupPolicysOutput{}
	req = c.newRequest(op, input, output)
	return
}

// DescribeSecurityGroupPolicys API operation for SecurityGroup.
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation DescribeSecurityGroupPolicys for usage and error information.
func (c *DFW) DescribeSecurityGroupPolicys(input *DescribeSecurityGroupPolicysInput) (*DescribeSecurityGroupPolicysOutput, error) {
	req, out := c.DescribeSecurityGroupPolicysRequest(input)
	return out, req.Send()
}

// DescribeSecurityGroupPolicysWithContext is the same as DescribeSecurityGroupPolicys with the addition of
// the ability to pass a context and additional request options.
//
// See DescribeSecurityGroupPolicys for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) DescribeSecurityGroupPolicysWithContext(ctx sdf.Context, input *DescribeSecurityGroupPolicysInput, opts ...request.Option) (*DescribeSecurityGroupPolicysOutput, error) {
	req, out := c.DescribeSecurityGroupPolicysRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

const opDescribeSecurityGroups = "DescribeSecurityGroupEx"

// DescribeSecurityGroupsRequest generates a "aws/request.Request" representing the
// client's request for the DescribeSecurityGroups operation. The "output" return
// value will be populated with the request's response once the request completes
// successfuly.
//
// Use "Send" method on the returned Request to send the API call to the service.
// the "output" return value is not valid until after Send returns without error.
//
// See DescribeSecurityGroups for more information on using the DescribeSecurityGroups
// API call, and error handling.
//
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
//
//
//    // Example sending a request using the DescribeSecurityGroupsRequest method.
//    req, resp := client.DescribeSecurityGroupsRequest(params)
//
//    err := req.Send()
//    if err == nil { // resp is now filled
//        fmt.Println(resp)
//    }
func (c *DFW) DescribeSecurityGroupsRequest(input *DescribeSecurityGroupsInput) (req *request.Request, output *DescribeSecurityGroupsOutput) {
	op := &request.Operation{
		Name:       opDescribeSecurityGroups,
		HTTPMethod: "GET",
		HTTPPath:   "/v2/index.php",
		Paginator: &request.Paginator{
			InputTokens:     []string{"Offset"},
			OutputTokens:    []string{"Detail.TotalCount"},
			LimitToken:      "Limit",
			TruncationToken: "",
		},
	}

	if input == nil {
		input = &DescribeSecurityGroupsInput{}
	}

	output = &DescribeSecurityGroupsOutput{}
	req = c.newRequest(op, input, output)
	return
}

// DescribeSecurityGroups API operation for SecurityGroup.
//
// 本接口 (DescribeSecurityGroup) ）用于根据多种索引查询一个或多个安全组的基本信息。
//
// 接口请求域名：dfw.api.qcloud.com
//
//    * 可以根据实例ID、实例名称或者实例计费模式等信息来查询实例的详细信息。过滤信息详细请见过滤器Filter。
//    * 如果参数为空，返回当前用户一定数量（Limit所指定的数量，默认为20）的实例。
//
// Returns awserr.Error for service API and SDK errors. Use runtime type assertions
// with awserr.Error's Code and Message methods to get detailed information about
// the error.
//
// See the AWS API reference guide for SecurityGroup's
// API operation DescribeSecurityGroups for usage and error information.
func (c *DFW) DescribeSecurityGroups(input *DescribeSecurityGroupsInput) (*DescribeSecurityGroupsOutput, error) {
	req, out := c.DescribeSecurityGroupsRequest(input)
	return out, req.Send()
}

// DescribeSecurityGroupsWithContext is the same as DescribeSecurityGroups with the addition of
// the ability to pass a context and additional request options.
//
// See DescribeSecurityGroups for details on how to use this API operation.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) DescribeSecurityGroupsWithContext(ctx sdf.Context, input *DescribeSecurityGroupsInput, opts ...request.Option) (*DescribeSecurityGroupsOutput, error) {
	req, out := c.DescribeSecurityGroupsRequest(input)
	req.SetContext(ctx)
	req.ApplyOptions(opts...)
	return out, req.Send()
}

// DescribeSecurityGroupsPages iterates over the pages of a DescribeSecurityGroups operation,
// calling the "fn" function with the response data for each page. To stop
// iterating, return false from the fn function.
//
// See DescribeSecurityGroups method for more information on how to use this operation.
//
// Note: This operation can generate multiple requests to a service.
//
//    // Example iterating over at most 3 pages of a DescribeSecurityGroups operation.
//    pageNum := 0
//    err := client.DescribeSecurityGroupsPages(params,
//        func(page *DescribeSecurityGroupsOutput, lastPage bool) bool {
//            pageNum++
//            fmt.Println(page)
//            return pageNum <= 3
//        })
//
func (c *DFW) DescribeSecurityGroupsPages(input *DescribeSecurityGroupsInput, fn func(*DescribeSecurityGroupsOutput, bool) bool) error {
	return c.DescribeSecurityGroupsPagesWithContext(sdf.BackgroundContext(), input, fn)
}

// DescribeSecurityGroupsPagesWithContext same as DescribeSecurityGroupsPages except
// it takes a Context and allows setting request options on the pages.
//
// The context must be non-nil and will be used for request cancellation. If
// the context is nil a panic will occur. In the future the SDK may create
// sub-contexts for http.Requests. See https://golang.org/pkg/context/
// for more information on using Contexts.
func (c *DFW) DescribeSecurityGroupsPagesWithContext(ctx sdf.Context, input *DescribeSecurityGroupsInput, fn func(*DescribeSecurityGroupsOutput, bool) bool, opts ...request.Option) error {
	p := request.Pagination{
		NewRequest: func() (*request.Request, error) {
			var inCpy *DescribeSecurityGroupsInput
			if input != nil {
				tmp := *input
				inCpy = &tmp
			}
			req, _ := c.DescribeSecurityGroupsRequest(inCpy)
			req.SetContext(ctx)
			req.ApplyOptions(opts...)
			return req, nil
		},
	}

	cont := true
	for p.Next() && cont {
		cont = fn(p.Page().(*DescribeSecurityGroupsOutput), !p.HasNextPage())
	}
	return p.Err()
}

type CreateSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	ProjectId *int64 `locationName:"projectId" type:"integer"`

	SgName *string `locationName:"sgName" type:"string"`

	SgRemark *string `locationName:"sgRemark" type:"string"`
}

// String returns the string representation
func (s CreateSecurityGroupInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateSecurityGroupInput) GoString() string {
	return s.String()
}

// SetProjectId sets the ProjectId field's value.
func (s *CreateSecurityGroupInput) SetProjectId(v int64) *CreateSecurityGroupInput {
	s.ProjectId = &v
	return s
}

// SetSgName sets the SgName field's value.
func (s *CreateSecurityGroupInput) SetSgName(v string) *CreateSecurityGroupInput {
	s.SgName = &v
	return s
}

// SetSgRemark sets the SgRemark field's value.
func (s *CreateSecurityGroupInput) SetSgRemark(v string) *CreateSecurityGroupInput {
	s.SgRemark = &v
	return s
}

type CreateSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"codc" type:"integer"`

	CodeDesc *string `locationName:"codeDesc" type:"string"`

	Data *SecurityGroup `locationName:"data" type:"structure"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s CreateSecurityGroupOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateSecurityGroupOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *CreateSecurityGroupOutput) SetCode(v int64) *CreateSecurityGroupOutput {
	s.Code = &v
	return s
}

// SetCodeDesc sets the CodeDesc field's value.
func (s *CreateSecurityGroupOutput) SetCodeDesc(v string) *CreateSecurityGroupOutput {
	s.CodeDesc = &v
	return s
}

// SetData sets the Data field's value.
func (s *CreateSecurityGroupOutput) SetData(v *SecurityGroup) *CreateSecurityGroupOutput {
	s.Data = v
	return s
}

// SetMessage sets the Message field's value.
func (s *CreateSecurityGroupOutput) SetMessage(v string) *CreateSecurityGroupOutput {
	s.Message = &v
	return s
}

type CreateSecurityGroupPolicyInput struct {
	_ struct{} `type:"structure"`

	Direction *string `locationName:"direction" type:"string"`

	Index *int64 `locationName:"index" type:"integer"`

	Policys []*SecurityGroupPolicy `locationName:"policys" type:"list" flattened:"true"`

	SgId *string `locationName:"sgId" type:"string"`

	Version *int64 `locationName:"version" type:"integer"`
}

// String returns the string representation
func (s CreateSecurityGroupPolicyInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateSecurityGroupPolicyInput) GoString() string {
	return s.String()
}

// SetDirection sets the Direction field's value.
func (s *CreateSecurityGroupPolicyInput) SetDirection(v string) *CreateSecurityGroupPolicyInput {
	s.Direction = &v
	return s
}

// SetIndex sets the Index field's value.
func (s *CreateSecurityGroupPolicyInput) SetIndex(v int64) *CreateSecurityGroupPolicyInput {
	s.Index = &v
	return s
}

// SetPolicys sets the Policys field's value.
func (s *CreateSecurityGroupPolicyInput) SetPolicys(v []*SecurityGroupPolicy) *CreateSecurityGroupPolicyInput {
	s.Policys = v
	return s
}

// SetSgId sets the SgId field's value.
func (s *CreateSecurityGroupPolicyInput) SetSgId(v string) *CreateSecurityGroupPolicyInput {
	s.SgId = &v
	return s
}

// SetVersion sets the Version field's value.
func (s *CreateSecurityGroupPolicyInput) SetVersion(v int64) *CreateSecurityGroupPolicyInput {
	s.Version = &v
	return s
}

type CreateSecurityGroupPolicyOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"code" type:"integer"`

	CodeDesc *string `locationName:"codeDesc" type:"string"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s CreateSecurityGroupPolicyOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateSecurityGroupPolicyOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *CreateSecurityGroupPolicyOutput) SetCode(v int64) *CreateSecurityGroupPolicyOutput {
	s.Code = &v
	return s
}

// SetCodeDesc sets the CodeDesc field's value.
func (s *CreateSecurityGroupPolicyOutput) SetCodeDesc(v string) *CreateSecurityGroupPolicyOutput {
	s.CodeDesc = &v
	return s
}

// SetMessage sets the Message field's value.
func (s *CreateSecurityGroupPolicyOutput) SetMessage(v string) *CreateSecurityGroupPolicyOutput {
	s.Message = &v
	return s
}

type DeleteSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	Region *string `locationName:"Region" type:"string" enum:"RegionEnum"`

	SgId *string `locationName:"sgId" type:"string"`
}

// String returns the string representation
func (s DeleteSecurityGroupInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteSecurityGroupInput) GoString() string {
	return s.String()
}

// SetRegion sets the Region field's value.
func (s *DeleteSecurityGroupInput) SetRegion(v string) *DeleteSecurityGroupInput {
	s.Region = &v
	return s
}

// SetSgId sets the SgId field's value.
func (s *DeleteSecurityGroupInput) SetSgId(v string) *DeleteSecurityGroupInput {
	s.SgId = &v
	return s
}

type DeleteSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"code" type:"integer"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s DeleteSecurityGroupOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteSecurityGroupOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *DeleteSecurityGroupOutput) SetCode(v int64) *DeleteSecurityGroupOutput {
	s.Code = &v
	return s
}

// SetMessage sets the Message field's value.
func (s *DeleteSecurityGroupOutput) SetMessage(v string) *DeleteSecurityGroupOutput {
	s.Message = &v
	return s
}

type DeleteSecurityGroupPolicyInput struct {
	_ struct{} `type:"structure"`

	Direction *string `locationName:"direction" type:"string"`

	Indexes []*int64 `locationName:"indexes" type:"list"`

	SgId *string `locationName:"sgId" type:"string"`

	Version *int64 `locationName:"version" type:"integer"`
}

// String returns the string representation
func (s DeleteSecurityGroupPolicyInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteSecurityGroupPolicyInput) GoString() string {
	return s.String()
}

// SetDirection sets the Direction field's value.
func (s *DeleteSecurityGroupPolicyInput) SetDirection(v string) *DeleteSecurityGroupPolicyInput {
	s.Direction = &v
	return s
}

// SetIndexes sets the Indexes field's value.
func (s *DeleteSecurityGroupPolicyInput) SetIndexes(v []*int64) *DeleteSecurityGroupPolicyInput {
	s.Indexes = v
	return s
}

// SetSgId sets the SgId field's value.
func (s *DeleteSecurityGroupPolicyInput) SetSgId(v string) *DeleteSecurityGroupPolicyInput {
	s.SgId = &v
	return s
}

// SetVersion sets the Version field's value.
func (s *DeleteSecurityGroupPolicyInput) SetVersion(v int64) *DeleteSecurityGroupPolicyInput {
	s.Version = &v
	return s
}

type DeleteSecurityGroupPolicyOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"code" type:"integer"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s DeleteSecurityGroupPolicyOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteSecurityGroupPolicyOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *DeleteSecurityGroupPolicyOutput) SetCode(v int64) *DeleteSecurityGroupPolicyOutput {
	s.Code = &v
	return s
}

// SetMessage sets the Message field's value.
func (s *DeleteSecurityGroupPolicyOutput) SetMessage(v string) *DeleteSecurityGroupPolicyOutput {
	s.Message = &v
	return s
}

type DescribeSecurityGroupData struct {
	_ struct{} `type:"structure"`

	Detail []*SecurityGroup `locationName:"detail" type:"list"`

	TotalNum *int64 `locationName:"totalNum" type:"integer"`
}

// String returns the string representation
func (s DescribeSecurityGroupData) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupData) GoString() string {
	return s.String()
}

// SetDetail sets the Detail field's value.
func (s *DescribeSecurityGroupData) SetDetail(v []*SecurityGroup) *DescribeSecurityGroupData {
	s.Detail = v
	return s
}

// SetTotalNum sets the TotalNum field's value.
func (s *DescribeSecurityGroupData) SetTotalNum(v int64) *DescribeSecurityGroupData {
	s.TotalNum = &v
	return s
}

type DescribeSecurityGroupPolicyData struct {
	_ struct{} `type:"structure"`

	Egress []*SecurityGroupPolicy `locationName:"egress" type:"list" flattened:"true"`

	Ingress []*SecurityGroupPolicy `locationName:"ingress" type:"list" flattened:"true"`
}

// String returns the string representation
func (s DescribeSecurityGroupPolicyData) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupPolicyData) GoString() string {
	return s.String()
}

// SetEgress sets the Egress field's value.
func (s *DescribeSecurityGroupPolicyData) SetEgress(v []*SecurityGroupPolicy) *DescribeSecurityGroupPolicyData {
	s.Egress = v
	return s
}

// SetIngress sets the Ingress field's value.
func (s *DescribeSecurityGroupPolicyData) SetIngress(v []*SecurityGroupPolicy) *DescribeSecurityGroupPolicyData {
	s.Ingress = v
	return s
}

type DescribeSecurityGroupPolicysInput struct {
	_ struct{} `type:"structure"`

	SgId *string `locationName:"sgId" type:"string"`
}

// String returns the string representation
func (s DescribeSecurityGroupPolicysInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupPolicysInput) GoString() string {
	return s.String()
}

// SetSgId sets the SgId field's value.
func (s *DescribeSecurityGroupPolicysInput) SetSgId(v string) *DescribeSecurityGroupPolicysInput {
	s.SgId = &v
	return s
}

type DescribeSecurityGroupPolicysOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"code" type:"integer"`

	CodeDesc *string `locationName:"codeDesc" type:"string"`

	Data *DescribeSecurityGroupPolicyData `locationName:"data" type:"structure"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s DescribeSecurityGroupPolicysOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupPolicysOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *DescribeSecurityGroupPolicysOutput) SetCode(v int64) *DescribeSecurityGroupPolicysOutput {
	s.Code = &v
	return s
}

// SetCodeDesc sets the CodeDesc field's value.
func (s *DescribeSecurityGroupPolicysOutput) SetCodeDesc(v string) *DescribeSecurityGroupPolicysOutput {
	s.CodeDesc = &v
	return s
}

// SetData sets the Data field's value.
func (s *DescribeSecurityGroupPolicysOutput) SetData(v *DescribeSecurityGroupPolicyData) *DescribeSecurityGroupPolicysOutput {
	s.Data = v
	return s
}

// SetMessage sets the Message field's value.
func (s *DescribeSecurityGroupPolicysOutput) SetMessage(v string) *DescribeSecurityGroupPolicysOutput {
	s.Message = &v
	return s
}

type DescribeSecurityGroupsInput struct {
	_ struct{} `type:"structure"`

	Limit *int64 `locationName:"Limit," type:"integer"`

	Offset *int64 `locationName:"Offset," type:"integer"`

	OffsetLine *int64 `locationName:"OffsetLine," type:"integer"`

	ProjectId *int64 `locationName:"ProjectId" type:"integer"`

	SgId *string `locationName:"SgId" type:"string"`

	SgName *string `locationName:"SgName" type:"string"`
}

// String returns the string representation
func (s DescribeSecurityGroupsInput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupsInput) GoString() string {
	return s.String()
}

// SetLimit sets the Limit field's value.
func (s *DescribeSecurityGroupsInput) SetLimit(v int64) *DescribeSecurityGroupsInput {
	s.Limit = &v
	return s
}

// SetOffset sets the Offset field's value.
func (s *DescribeSecurityGroupsInput) SetOffset(v int64) *DescribeSecurityGroupsInput {
	s.Offset = &v
	return s
}

// SetOffsetLine sets the OffsetLine field's value.
func (s *DescribeSecurityGroupsInput) SetOffsetLine(v int64) *DescribeSecurityGroupsInput {
	s.OffsetLine = &v
	return s
}

// SetProjectId sets the ProjectId field's value.
func (s *DescribeSecurityGroupsInput) SetProjectId(v int64) *DescribeSecurityGroupsInput {
	s.ProjectId = &v
	return s
}

// SetSgId sets the SgId field's value.
func (s *DescribeSecurityGroupsInput) SetSgId(v string) *DescribeSecurityGroupsInput {
	s.SgId = &v
	return s
}

// SetSgName sets the SgName field's value.
func (s *DescribeSecurityGroupsInput) SetSgName(v string) *DescribeSecurityGroupsInput {
	s.SgName = &v
	return s
}

type DescribeSecurityGroupsOutput struct {
	_ struct{} `type:"structure"`

	Code *int64 `locationName:"code" type:"integer"`

	CodeDesc *string `locationName:"codeDesc" type:"string"`

	Data *DescribeSecurityGroupData `locationName:"data" type:"structure"`

	Message *string `locationName:"message" type:"string"`
}

// String returns the string representation
func (s DescribeSecurityGroupsOutput) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeSecurityGroupsOutput) GoString() string {
	return s.String()
}

// SetCode sets the Code field's value.
func (s *DescribeSecurityGroupsOutput) SetCode(v int64) *DescribeSecurityGroupsOutput {
	s.Code = &v
	return s
}

// SetCodeDesc sets the CodeDesc field's value.
func (s *DescribeSecurityGroupsOutput) SetCodeDesc(v string) *DescribeSecurityGroupsOutput {
	s.CodeDesc = &v
	return s
}

// SetData sets the Data field's value.
func (s *DescribeSecurityGroupsOutput) SetData(v *DescribeSecurityGroupData) *DescribeSecurityGroupsOutput {
	s.Data = v
	return s
}

// SetMessage sets the Message field's value.
func (s *DescribeSecurityGroupsOutput) SetMessage(v string) *DescribeSecurityGroupsOutput {
	s.Message = &v
	return s
}

type SecurityGroup struct {
	_ struct{} `type:"structure"`

	BeAssociateCount *int64 `locationName:"beAssociateCount" type:"integer"`

	CreateTime *string `locationName:"createTime" type:"string"`

	SgId *string `locationName:"sgId" type:"string"`

	SgName *string `locationName:"sgName" type:"string"`

	SgRemark *string `locationName:"sgRemark" type:"string"`

	Version *int64 `locationName:"version" type:"integer"`
}

// String returns the string representation
func (s SecurityGroup) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s SecurityGroup) GoString() string {
	return s.String()
}

// SetBeAssociateCount sets the BeAssociateCount field's value.
func (s *SecurityGroup) SetBeAssociateCount(v int64) *SecurityGroup {
	s.BeAssociateCount = &v
	return s
}

// SetCreateTime sets the CreateTime field's value.
func (s *SecurityGroup) SetCreateTime(v string) *SecurityGroup {
	s.CreateTime = &v
	return s
}

// SetSgId sets the SgId field's value.
func (s *SecurityGroup) SetSgId(v string) *SecurityGroup {
	s.SgId = &v
	return s
}

// SetSgName sets the SgName field's value.
func (s *SecurityGroup) SetSgName(v string) *SecurityGroup {
	s.SgName = &v
	return s
}

// SetSgRemark sets the SgRemark field's value.
func (s *SecurityGroup) SetSgRemark(v string) *SecurityGroup {
	s.SgRemark = &v
	return s
}

// SetVersion sets the Version field's value.
func (s *SecurityGroup) SetVersion(v int64) *SecurityGroup {
	s.Version = &v
	return s
}

type SecurityGroupPolicy struct {
	_ struct{} `type:"structure"`

	Action *string `locationName:"action" type:"string"`

	AddressModule *string `locationName:"addressModule" type:"string"`

	CidrIp *string `locationName:"cidrIp" type:"string"`

	Desc *string `locationName:"desc" type:"string"`

	IpProtocol *string `locationName:"ipProtocol" type:"string"`

	Key *int64 `locationName:"key" type:"integer"`

	PortRange *string `locationName:"portRange" type:"string"`

	ServiceModule *string `locationName:"serviceModule" type:"string"`

	SgId *string `locationName:"sgId" type:"string"`
}

// String returns the string representation
func (s SecurityGroupPolicy) String() string {
	return sdfutil.Prettify(s)
}

// GoString returns the string representation
func (s SecurityGroupPolicy) GoString() string {
	return s.String()
}

// SetAction sets the Action field's value.
func (s *SecurityGroupPolicy) SetAction(v string) *SecurityGroupPolicy {
	s.Action = &v
	return s
}

// SetAddressModule sets the AddressModule field's value.
func (s *SecurityGroupPolicy) SetAddressModule(v string) *SecurityGroupPolicy {
	s.AddressModule = &v
	return s
}

// SetCidrIp sets the CidrIp field's value.
func (s *SecurityGroupPolicy) SetCidrIp(v string) *SecurityGroupPolicy {
	s.CidrIp = &v
	return s
}

// SetDesc sets the Desc field's value.
func (s *SecurityGroupPolicy) SetDesc(v string) *SecurityGroupPolicy {
	s.Desc = &v
	return s
}

// SetIpProtocol sets the IpProtocol field's value.
func (s *SecurityGroupPolicy) SetIpProtocol(v string) *SecurityGroupPolicy {
	s.IpProtocol = &v
	return s
}

// SetKey sets the Key field's value.
func (s *SecurityGroupPolicy) SetKey(v int64) *SecurityGroupPolicy {
	s.Key = &v
	return s
}

// SetPortRange sets the PortRange field's value.
func (s *SecurityGroupPolicy) SetPortRange(v string) *SecurityGroupPolicy {
	s.PortRange = &v
	return s
}

// SetServiceModule sets the ServiceModule field's value.
func (s *SecurityGroupPolicy) SetServiceModule(v string) *SecurityGroupPolicy {
	s.ServiceModule = &v
	return s
}

// SetSgId sets the SgId field's value.
func (s *SecurityGroupPolicy) SetSgId(v string) *SecurityGroupPolicy {
	s.SgId = &v
	return s
}

const (
	// RegionEnumApBeijing is a RegionEnum enum value
	RegionEnumApBeijing = "ap-beijing"

	// RegionEnumApChengdu is a RegionEnum enum value
	RegionEnumApChengdu = "ap-chengdu"

	// RegionEnumApGuangzhou is a RegionEnum enum value
	RegionEnumApGuangzhou = "ap-guangzhou"

	// RegionEnumApGuangzhouOpen is a RegionEnum enum value
	RegionEnumApGuangzhouOpen = "ap-guangzhou-open"

	// RegionEnumApHongkong is a RegionEnum enum value
	RegionEnumApHongkong = "ap-hongkong"

	// RegionEnumApShanghai is a RegionEnum enum value
	RegionEnumApShanghai = "ap-shanghai"

	// RegionEnumApSingapore is a RegionEnum enum value
	RegionEnumApSingapore = "ap-singapore"

	// RegionEnumEuFrankfurt is a RegionEnum enum value
	RegionEnumEuFrankfurt = "eu-frankfurt"

	// RegionEnumNaSiliconvalley is a RegionEnum enum value
	RegionEnumNaSiliconvalley = "na-siliconvalley"

	// RegionEnumNaToronto is a RegionEnum enum value
	RegionEnumNaToronto = "na-toronto"

	// RegionEnumApShanghaiFsi is a RegionEnum enum value
	RegionEnumApShanghaiFsi = "ap-shanghai-fsi"

	// RegionEnumApShenzhenFsi is a RegionEnum enum value
	RegionEnumApShenzhenFsi = "ap-shenzhen-fsi"
)
