// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package dfw provides the client and types for making API
// requests to SecurityGroup.
//
// 欢迎使用安全组（SecurityGroup）
//
// 腾讯安全组（SecurityGroup，以下又称DFW）运行在腾讯数据中心，它提供了可以弹性伸缩的计算服务，可以根据业务需要来构建和托管软件系统。
//
// 云服务器向用户提供弹性的计算、存储和网络资源。用户可以使用本文档介绍的 API，并参照相应的示例，对云服务器进行相关操作：如创建、销毁、更改带宽、重启等；支持的全部操作可参见API概览页
// (https://cloud.tencent.com/document/api/213/1232)。
//
// See dfw package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/dfw/
//
// Using the Client
//
// To contact SecurityGroup with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See sdf.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the SecurityGroup client DFW for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/dfw/#New
package dfw
