// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package cvm_test

import (
	"fmt"
	"strings"
	"time"

	"github.com/polefishu/sdk-builder/sdf"
	"github.com/polefishu/sdk-builder/sdf/sdferr"
	"github.com/polefishu/sdk-builder/sdf/session"
	"github.com/polefishu/sdk-builder/service/tencentcloud/cvm"
)

var _ time.Duration
var _ strings.Reader
var _ sdf.Config

func parseTime(layout, value string) *time.Time {
	t, err := time.Parse(layout, value)
	if err != nil {
		panic(err)
	}
	return &t
}

// To describe instances
//
// This example DescribeInstances.
func ExampleCVM_DescribeInstances_shared00() {
	svc := cvm.New(session.New())
	input := &cvm.DescribeInstancesInput{}

	result, err := svc.DescribeInstances(input)
	if err != nil {
		if serr, ok := err.(sdferr.Error); ok {
			switch serr.Code() {
			default:
				fmt.Println(serr.Error())
			}
		} else {
			// Print the error, cast err to sdferr.Error to get the Code and
			// Message from an error.
			fmt.Println(err.Error())
		}
		return
	}

	fmt.Println(result)
}
